# Generated by Django 3.1.5 on 2021-07-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(blank=True, default='000', max_length=100)),
                ('Title', models.CharField(blank=True, default='', max_length=200)),
                ('Description', models.CharField(blank=True, default='', max_length=2000)),
                ('Images', models.CharField(blank=True, default='', max_length=1000)),
                ('Mobile', models.CharField(blank=True, default='', max_length=200)),
                ('Age', models.PositiveIntegerField(blank=True, default=0)),
                ('Price', models.PositiveIntegerField(blank=True, default=0)),
                ('Location', models.CharField(blank=True, default='', max_length=200)),
                ('CountryID', models.IntegerField(blank=True, default=0)),
                ('StateID', models.IntegerField(blank=True, default=0)),
                ('CityID', models.CharField(blank=True, default='', max_length=200)),
                ('CityURL', models.CharField(blank=True, default='', max_length=200)),
                ('Section', models.CharField(blank=True, default='', max_length=200)),
                ('Category', models.CharField(blank=True, default='', max_length=200)),
                ('CateoryURL', models.CharField(blank=True, default='', max_length=200)),
                ('Scrap', models.PositiveIntegerField(blank=True, default=2)),
                ('Status', models.PositiveIntegerField(blank=True, default=1)),
                ('StartDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
