# Generated by Django 3.1.5 on 2021-07-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subito',
            name='Category',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subito',
            name='CityID',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='subito',
            name='Section',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
