# Generated by Django 3.1.5 on 2021-07-05 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0002_auto_20210705_0351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subito',
            old_name='CateoryURL',
            new_name='CategoryURL',
        ),
    ]
